### ISSUE TITLE
Softbreak and Hardbreak

### ISSUE THREAD

**Issue by iamstarkov** [jgm/commonmark.js#46]
Accordingly to readme and [code](https://github.com/jgm/commonmark.js/blob/7df3ca7189642446b2863b2f0686e8849251bf15/lib/inlines.js#L729-L744) there are two types of breaks: Softbreak and Hardbreak. Hardbreak prepended by double space, but then I cannot understand how Softbreak is detected. Can you help me?

```
## Expected
Input: "YOLO  \nmd ftw\n"
AST:
  Document: null
  Paragraph: null
  Text: YOLO
  Hardbreak: null // it’s fine, it’s how it is suppoused to be
  Text: md ftw
  Paragraph: null
  Document: null

## Not Expected
Input: "YOLO\n\n\nmd ftw\n"
AST:
  Document: null
  Paragraph: null
  Text: YOLO
  // where is Softbreak here?
  Paragraph: null
  Paragraph: null
  Text: md ftw
  Paragraph: null
  Document: null
```
